services:
  explore_nest:
    build:
      context: ./www
      dockerfile: Dockerfile
    container_name: nest_explore_city
    depends_on:
      - explore_mysql
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - internal
    volumes:
      - ./www:/app
      - /app/node_modules
    command: npm run start:dev

  explore_mysql:
    image: mysql:latest
    container_name: mysql_explore_city
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - internal
    ports:
      - '8446:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 5s
      retries: 10

networks:
  internal:
    driver: bridge